config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :campaign
  resources :answer

  root to: "campaign#index"

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :campaign
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/campaign.rb
class Campaign < ApplicationRecord
  enum medium: {bot: 1, form: 2}

  has_many :campaign_sectors, dependent: :destroy
  has_many :sectors, through: :campaign_sectors

  has_many :answers
end

app/models/campaign_sector.rb
class CampaignSector < ApplicationRecord
  belongs_to :campaign
  belongs_to :sector
end

app/models/sector.rb
class Sector < ApplicationRecord
  has_many :users

  has_many :campaign_sectors, dependent: :destroy
  has_many :campaigns, through: :campaign_sectors
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :sector
  has_many :answer

  enum role: {direction: 1, gerency: 2, coordination: 3, user: 4}
end

app/controllers/answer_controller.rb
class AnswerController < ApplicationController

  def index
    @campaign = Campaign.find(params[:campaign_id])
  end

  def new 
    @campaign = Campaign.find(params[:campaign_id])
    @user = User.find(params[:user_id])
  end

  def create
    @answer = Answer.new(answer_params)
    
    if @answer.save
      respond_to do |format|
        format.html { redirect_to answer_index_path(campaign_id: @answer.campaign.id) }
      end
    else
      puts @answer.errors.full_messages
      respond_to do |format|
        format.html { redirect_to campaign_index_path, alert: "Error creating Campaign." }
      end
    end
  end

  private
    def answer_params
      params.require(:answer).permit(:text, :campaign_id, :user_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/campaign_controller.rb
class CampaignController < ApplicationController
  before_action :authenticate_user!

  def index
    @campaigns = Campaign.all
  end

  def show
    @campaign = Campaign.find(params[:id])
  end

  def create
    @campaign = Campaign.new(campaign_params)
    if @campaign.save
      if @campaign.medium == 'form'
        recepient = @campaign.sectors.map { |s| s.users }.flatten
        recepient.each do |r| 
          ApplicationMailer.with(campaign: @campaign, user: r).campaign_email.deliver_now
        end
      else
        puts "WIP: connect to bot"
      end
      respond_to do |format|
        format.html { redirect_to campaign_path(@campaign.id) }
      end
    else
      respond_to do |format|
        format.html { redirect_to campaign_path, alert: "Error creating Campaign." }
      end
    end
  end

  private
    def campaign_params
      _params = params.require(:campaign).permit(:name, :text, :medium, :sector_ids)
      _params[:sector_ids] = _params[:sector_ids].split(',')
      return _params
    end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:sector_id])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:sector_id])
  end
end

app/helpers/answer_helper.rb
module AnswerHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/campaign_helper.rb
module CampaignHelper
end

app/views/answer/index.html.erb
<h1>RESPOSTAS DA CAMPANHA <%= @campaign.name %></h1>
<div class="campaign-wrapper">
  <% @campaign.answers.each do |ans| %>
    <div class="campaign-card">
      <p><%= ans.text %></p>
      <div>
      <p> Setor: <%= ans.user.sector.name %></p>
      </div> 
    </div> 
  <% end %>
</div> 
  
<div class="links">
  <%= link_to "Nova campanha", new_campaign_path %>
  <%= link_to "Ver todas campanhas", campaign_index_path %>
</div>

app/views/answer/new.html.erb
<main>
  <div class="box" style="align-items: center;">
    <h1>NOVA RESPOSTA</h1>
    <h1><%= @campaign.name %></h1>
    <p><%= @campaign.text %></p>
    
    <%= form_with model: Answer.new, url: answer_index_path do |f| %>
      <div class="tfield">
        <%= f.label :text %><br />
        <%= f.text_area :text, autofocus: true, autocomplete: "text", rows: 5 %>
      </div>
      <%= f.hidden_field :campaign_id, value: params[:campaign_id] %>
      <%= f.hidden_field :user_id, value: params[:user_id] %>
      <div class="actions">
        <%= f.submit "Submit" %>
      </div>
    <% end %>
  </div>
</main>

app/views/campaign/index.html.erb
<h1>Campanhas disponíveis</h1>
<div class="campaign-wrapper">
  <% @campaigns.each do |c| %>
    <div class="campaign-card">
      <p><%= c.name %></p>
      <div>
      <p> Setores:</p>
      <% c.sectors.each do |s| %>
        <p><%= s.name %></p>        
      <% end %>
      </div> 
      <div class="links">
        <%= link_to "Responder", new_answer_path(campaign_id: c.id, user_id: current_user) %>
        <%= link_to "Ver todas respostas", answer_index_path(campaign_id: c.id) %>
      </div> 
    </div> 
  <% end %>
</div> 
  
<div class="links">
  <%= link_to "Nova campanha", new_campaign_path %>
</div>

app/views/campaign/new.html.erb
<main>
  <div class="box">
    <h1>NOVA CAMPANHA</h1>
    <%= form_with model: Campaign.new, url: campaign_index_path do |f| %>
      <div class="tfield">
        <%= f.label :name %><br />
        <%= f.text_field :name, autofocus: true, autocomplete: "text" %>
      </div>
      <div class="tfield">
        <%= f.label :text %><br />
        <%= f.text_area :text, autofocus: true, autocomplete: "text", rows: 5 %>
      </div>
      <div class="radio-button-wrapper">
        <div class="field">
          <%= f.radio_button :medium, "bot" %>
          <%= f.label :medium, "Chatbot", value: 'bot' %>
        </div>
        <div class="field">
          <%= f.radio_button :medium, "form" %>
          <%= f.label :medium, "Form", value: "form" %>
        </div>
      </div>
      <div class="checkbox-wrapper" data-controller="check-multiple">
        <% Sector.all.each do |s| %>
          <div class="field">
            <%= f.check_box "sector_#{s.id}", {data: {action: "check-multiple#toggle"}}, s.id %>
            <%= f.label "sector_#{s.id}", s.name %>
          </div>
        <% end %>
        <%= f.hidden_field :sector_ids, "data-check-multiple-target": "hiddenField" %>
      </div>
      <div class="actions">
        <%= f.submit "SALVAR" %>
      </div>
    <% end %>
  </div>
</main>

app/views/campaign/show.html.erb
<h1>DETALHES DA CAMPANHA</h1>
<p><%= @campaign.name %></p>
<p><%= @campaign.medium %></p>
<div class="links">
  <%= link_to "Ver todas respostas", answer_index_path(campaign_id: @campaign.id) %>
  <%= link_to "Responder", new_answer_path(campaign_id: @campaign.id, user_id: current_user) %>
</div>
<div class="links">
  <%= link_to "Ver todas campanhas", campaign_index_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Balde de Inovações</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= favicon_link_tag "https://cdn-icons-png.flaticon.com/512/4599/4599134.png" %>
  </head>

  <body>
    <%= button_to "LOGOUT", destroy_user_session_path, method: :delete, style: "position: absolute;right: 10px;top:10px" %>
    <%= yield %>
  </body>
</html>